### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by shri360** [dhirajms/kernel-Moto-C-plus#2]
drivers/input/dtv/fc8180_spi.c:36:20: fatal error: mt_spi.h: No such file or directory
 #include <mt_spi.h>
                    ^
compilation terminated.
make[3]: *** [drivers/input/dtv/fc8180_spi.o] Error 1
make[2]: *** [drivers/input/dtv] Error 2
make[2]: *** Waiting for unfinished jobs....
  CC      sound/soc/mediatek/mt_soc_audio_v3/mt_soc_pcm_mrgrx_awb.o
  CC      sound/soc/mediatek/mt_soc_audio_v3/mt_soc_pcm_fm_i2s.o
  LD      drivers/input/misc/built-in.o
make[1]: *** [drivers/input] Error 2
make: *** [drivers] Error 2

**Comment by dhirajms** [comment]
i will check tomorrow...

**Comment by shri360** [comment]
Fixed personally...
compiled successfully...
closing issue.
